#!/usr/bin/env node
// 生成版本信息，包括git提交次数作为内部版本号
// 同时同步到 Android 的 tauri.properties
import { execSync } from 'child_process';
import { readFileSync, writeFileSync, existsSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const projectRoot = join(__dirname, '..');

// 读取package.json获取主版本号
const packageJsonPath = join(projectRoot, 'package.json');
const packageJson = JSON.parse(readFileSync(packageJsonPath, 'utf-8'));
const appVersion = packageJson.version;

function writeIfChanged(filePath, content) {
  if (existsSync(filePath)) {
    const current = readFileSync(filePath, 'utf-8');
    if (current === content) {
      return false;
    }
  }

  writeFileSync(filePath, content, 'utf-8');
  return true;
}

// 获取git总提交次数作为build number
// ★ 版本基数：新仓库从 13000 起步，确保高于旧仓库所有历史版本
const VERSION_CODE_BASE = 13000;
let gitCommitCount = 0;
try {
  gitCommitCount = parseInt(execSync('git rev-list --all --count', { cwd: projectRoot, encoding: 'utf-8' }).trim(), 10) || 0;
} catch (error) {
  console.warn('Warning: Failed to get git commit count, using 0');
}
const buildNumber = String(VERSION_CODE_BASE + gitCommitCount);

// 获取 git short commit hash（用于精确追溯构建版本）
let gitHash = 'unknown';
try {
  gitHash = execSync('git rev-parse --short=8 HEAD', { cwd: projectRoot, encoding: 'utf-8' }).trim();
} catch (error) {
  console.warn('Warning: Failed to get git commit hash, using "unknown"');
}

// 生成版本信息TypeScript文件
const versionTsContent = `// 此文件由 scripts/generate-version.mjs 自动生成，请勿手动修改
export const VERSION_INFO = {
  APP_VERSION: '${appVersion}', // 应用主版本号
  BUILD_NUMBER: '${buildNumber}', // 内部版本号（git提交次数）
  GIT_HASH: '${gitHash}', // Git commit short hash
  FULL_VERSION: '${appVersion} (${buildNumber})', // 完整版本号
  SENTRY_RELEASE: '${appVersion}+${buildNumber}', // Sentry release 标识
} as const;

export default VERSION_INFO;
`;

const versionTsPath = join(projectRoot, 'src', 'version.ts');
writeIfChanged(versionTsPath, versionTsContent);

console.log(`✅ 版本信息已生成:`);
console.log(`   主版本号: ${appVersion}`);
console.log(`   内部版本号: ${buildNumber}`);
console.log(`   Git Hash: ${gitHash}`);
console.log(`   完整版本: ${appVersion} (${buildNumber})`);
console.log(`   Sentry Release: ${appVersion}+${buildNumber}`);
console.log(`   文件路径: ${versionTsPath}`);

// 同步到 Android tauri.properties（如果存在）
const tauriPropertiesPath = join(projectRoot, 'src-tauri', 'gen', 'android', 'app', 'tauri.properties');
if (existsSync(tauriPropertiesPath)) {
  const tauriPropertiesContent = `// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
tauri.android.versionName=${appVersion}
tauri.android.versionCode=${buildNumber}`;
  writeIfChanged(tauriPropertiesPath, tauriPropertiesContent);
  console.log(`✅ Android versionCode 已同步: ${buildNumber}`);
  console.log(`   文件路径: ${tauriPropertiesPath}`);
}

// 同步到 tauri.conf.json（确保 Android versionCode 使用 git 版本号）
const tauriConfigPath = join(projectRoot, 'src-tauri', 'tauri.conf.json');
if (existsSync(tauriConfigPath)) {
  try {
    const raw = readFileSync(tauriConfigPath, 'utf-8');
    const config = JSON.parse(raw);
    if (!config.bundle) config.bundle = {};
    if (!config.bundle.android) config.bundle.android = {};
    const numericBuildNumber = Number(buildNumber);
    config.bundle.android.versionCode = Number.isNaN(numericBuildNumber) ? 1 : numericBuildNumber;
    writeIfChanged(tauriConfigPath, JSON.stringify(config, null, 2) + '\n');
    console.log(`✅ tauri.conf.json 已写入 Android versionCode: ${config.bundle.android.versionCode}`);
  } catch (error) {
    console.warn('Warning: Failed to update tauri.conf.json for Android versionCode');
  }
}
